baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Hugo Website"
theme = "ananke"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 1

