baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "Chloé Dequeker"
theme = "hugo-theme-stack"

[taxonomies]
  countries = "countries"
  category  = "categories"
  tag       = "tags"

[params]
  description = "foo bar"
  featuredImageField = "featured_image"
  mainSections = ["wheeling-the-world"]

  [params.sidebar]
    compact = false

  [[params.widgets.page]]
    type = "continents"

  [[params.widgets.page]]
    type = "tag-countries"
    params.limit = 50
  [[params.widgets.homepage]]
    type = "continents"

  [[params.widgets.homepage]]
    type = "tag-countries"
    params.limit = 50

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -1
    [menu.main.params]
        icon = "home"
        newTab = false

  [[menu.main]]
    identifier = "wheeling-the-world"
    name = "Wheeling the world"
    url = "/wheeling-the-world/"
    weight = 1
    [menu.main.params]
        icon = "bike"
        newTab = false

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 1
    [menu.main.params]
        icon = "home"
        newTab = false

