baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "Chloé Dequeker"
theme = "hugo-theme-stack"

# [[module.imports]]
# path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
  description = "foo bar"
  featuredImageField = "featured_image"
  mainSections = ["home", "wheeling-the-world"]

# mainSections = ["wheeling-the-world"]
  # avatar.src = "profile_picture.jpg"
  [params.sidebar]
    compact = false
  [[params.widgets.page]]
    type = "page"
  [[params.widgets.page]]
    type = "archives"
  [[params.widgets.homepage]]
    type = "page"
  [[params.widgets.homepage]]
    type = "archives"

  [[params.widgets.homepage]]
    type = "categories"

  [[params.widgets.homepage]]
    type = "tag-countries"
  [[params.widgets.homepage]]
    type = "tag-cloud"

  [[params.widgets.page]]
    type = "categories"

  [[params.widgets.page]]
    type = "tag-countries"
  [[params.widgets.page]]
    type = "tag-cloud"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -1
    [menu.main.params]
        icon = "home"
        newTab = false

  [[menu.main]]
    identifier = "wheeling-the-world"
    name = "Wheeling the world"
    url = "/wheeling-the-world/"
    weight = 1
    [menu.main.params]
        icon = "bike"
        newTab = false

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 1
    [menu.main.params]
        icon = "home"
        newTab = false

